# Generated by Django 5.0.3 on 2024-03-26 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connexion',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server', models.CharField(max_length=150, unique=True, verbose_name='Server')),
                ('types', models.CharField(blank=True, choices=[('x3v7', 'AGRI'), ('x3sql', 'SMTP'), ('sage100', 'Sage100')], max_length=50, null=True, verbose_name='Type de la base')),
                ('login', models.CharField(default='reader', max_length=50, null=True, verbose_name='Identifiant')),
                ('password', models.CharField(default='m1234', max_length=500, verbose_name='Mot de Passe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('value', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=False)),
                ('base', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connexion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.connexion')),
            ],
        ),
    ]
