# Generated by Django 5.0.3 on 2024-03-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='base',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
