# Generated by Django 5.0.3 on 2024-03-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_societe_base'),
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access',
            field=models.ManyToManyField(blank=True, to='app.societe'),
        ),
    ]
